### ISSUE TITLE
(Regex issue?) Tags with aliases don't work.

### ISSUE THREAD

**Issue by Asinin3** [dnsev-h/ehentai-archive-info#1]
When running this program on a gallery with aliases for instance a Fate series gallery that has the:
`character:saber | arturia pendragon` tag only `character:saber` is gathered. Weirdly enough, when you click on these tags on eh/ex and click "Show Tagged Galleries" only `character:saber$` is put in the search field. However eze and /x/ Gallery Metadata include the full `character:saber | arturia pendragon` tag.

**Comment by dnsev-h** [comment]
It appears that using [the API](https://ehwiki.org/wiki/API) does not return alternate tag information. For example, requesting 466310/7ce6637602 results in the following JSON data:

```jsonc
{
  "gmetadata": [
    {
      "gid": 466310,
      "token": "7ce6637602",
      "archiver_key": "438763--6016027cd7c0be7d508399eab6374b30dea88639",
      "title": "(C81) [Jishou Seijunha (Hiroyuki)] Fubin Sugiru Zero Saber o Motto Ijimetai | I Want to Tease Poor Zero Saber More (Fate\/Zero) [English] [life4Kaoru]",
      "title_jpn": "(C81) [\u81ea\u79f0\u6e05\u7d14\u6d3e (\u30d2\u30ed\u30e6\u30ad)] \u4e0d\u61ab\u3059\u304e\u308b\u30bc\u30ed\u30bb\u30a4\u30d0\u30fc\u3092\u3082\u3063\u3068\u3044\u3058\u3081\u305f\u3044 (Fate\/Zero) [\u82f1\u8a33]",
      "category": "Non-H",
      "thumb": "https:\/\/ehgt.org\/c9\/b3\/c9b300d63e34bbfbd9cf9e490e18132eb0c23f71-1004026-1127-1600-jpg_l.jpg",
      "uploader": "ChansuLuck",
      "posted": "1329368291",
      "filecount": "27",
      "filesize": 8402543,
      "expunged": false,
      "rating": "4.80",
      "torrentcount": "0",
      "torrents": [],
      "tags": [
        "language:english",
        "language:translated",
        "parody:fate zero",
        "character:irisviel von einzbern",
        "character:kiritsugu emiya",
        "character:saber", /* note that this is only" saber" */
        "group:jishou seijunha",
        "artist:hiroyuki"
      ]
    }
  ]
}
```

Since this script uses this API to fetch gallery info, this issue cannot be fixed without switching to scraping webpage HTML which would add significant additional complexity.
