### ISSUE TITLE
(Suggestion) If json file exists, use it to find the gallery

### ISSUE THREAD

**Issue by Asinin3** [dnsev-h/ehentai-archive-info#2]
If there's already a json file in an archive and you are trying to update the tags, I think it would be a lot faster to scan the json for the gallery id and other relevant information instead of simply searching by image hash as usual and potentially using the file-upload for similar matches if it can't find anything.

This should be faster and more reliable while also cutting down on page-visits helping stop users get IP banned as quickly when updating gallery tags.

**Comment by dnsev-h** [comment]
Added in v2.0.1. See `updateMetadataIfExists` in [config.md](https://github.com/dnsev-h/ehentai-archive-info/blob/master/config.md).

**Comment by Asinin3** [comment]
Thanks!
