### ISSUE TITLE
Error: Failed to Parse Config

### ISSUE THREAD

**Issue by Tenome** [dnsev-h/ehentai-archive-info#4]
I tried dragging a cbz onto the batch file after setting up the 7-zip directory, but it keeps giving me this error. The log file is also empty. Below is the relevant text in the main.js. Any idea what might be causing this?

	let config;
	try {
		config = JSON.parse(configSource);
	} catch (e) {
		process.stderr.write("Failed to parse config\n");
		return -3;
	}

**Comment by dnsev-h** [comment]
Share your config file, something is probably incorrectly formatted in it (invalid JSON).

**Comment by Tenome** [comment]
Huh, it's working now. When I originally tried it, it gave me the error, so I thought that I had to fix the 7Zip directory path in the config. I also cleared the node cache and it gave me the same error. However, deleting everything and running from scratch works now for some reason. Well, whatever, you can close this. Thanks for the useful program.
